#!/bin/bash
# Creating aand Activating Python Virtual Environment

PY_REQ=$1

if [[ ! -f "$PY_REQ" ]]
then
    echo "Please specify Pip requirements files... Choose from the following"
    echo $(ls | grep "requirements")
    exit 1
fi 

if [[ "$PY_REQ" != "requirements_docker.txt" ]]
then
    echo "Creating Python Virtual Environment"
    python3 -m venv tf-utils-venv
    source tf-utils-venv/bin/activate
fi

pip install --upgrade pip
pip install Cython
pip install opencv-python
# Installing Python package requirements
pip install -r $PY_REQ
pip install keras
pip install matplotlib
echo "Python Package Requirements Installed Sucessfully!!"

# Setting Up DataSet directory and setting environment variables
mkdir DataSets
source activate

# Building protobufs
#cd scripts/TFUtils/models/research/
#protoc object_detection/protos/*.proto --python_out=.

# Testing Installation
#python object_detection/model_lib_test.py
#cd $TFUTILS_ROOT
#echo "Official TensorFlow research tools have passed all tests!!"
#python scripts/test.py --all
#echo "IMPL TensorFlow Utils have passed all tests!!"


if [[ "$PY_REQ" != "requirements_docker.txt" ]]
then
    # Deactivating Virtual Environment
    deactivate
fi
